### ISSUE TITLE
[v1] Required functions

### ISSUE THREAD

**Issue by aliceclv** [aliceclv/libft#1]
## Part 1

- [ ] memset
- [ ] bzero
- [ ] memcpy
- [ ] memccpy
- [ ] memmove
- [ ] memchr
- [ ] memcmp
- [ ] strlen
- [ ] isalpha
- [ ] isdigit
- [ ] isalnum
- [ ] isascii
- [ ] isprint
- [ ] toupper
- [ ] tolower
- [ ] strchr
- [ ] strrchr
- [ ] strncmp
- [ ] strlcpy
- [ ] strlcat
- [ ] strnstr
- [ ] atoi
- [ ] calloc
- [ ] strdup

## Part 2
- [ ] ft_substr
- [ ] ft_strjoin
- [ ] ft_strtrim
- [ ] ft_split
- [ ] ft_itoa
- [ ] ft_strmapi
- [ ] ft_putchar_fd
- [ ] ft_putstr_fd
- [ ] ft_putendl_fd
- [ ] ft_putnbr_fd

## Bonus
[TBD]
